[job]
dump_folder = "./outputs/llama3_1b_1_16"
description = "Llama 3 1B with linear attention (1:16 ratio)"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "llama3_linear"
flavor = "1B_4_16"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm
tokenizer_path = "/mbz/users/haolong.jia/opt/models/llama3/tokenizer.model"


[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 4 # macro_batch_size
seq_len = 4096
warmup_steps = 2000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 11727
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "fineweb_edu_100B"
gradient_accumulation_steps = 4 # 4 * 32 * 4 = 512

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 1000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
