[job]
dump_folder = "/mnt/sharefs/users/haolong.jia/attn/ckpts/nsa_8_16_even"
description = "llama3 with NSA, ratio 0.5 (8 NSA block), 1 Attention 1 NSA, union insert"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = true

[model]
name = "llama3_nsa"
flavor = "nsa_1B_8_16"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm
tokenizer_path = "/mnt/weka/home/haolong.jia/opt/model/tokenizer.model"


[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 4 # macro_batch_size
seq_len = 4096
warmup_steps = 4900  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 28662
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "fineweb_edu_100B"
gradient_accumulation_steps = 4 # 4 * 32 * 4 = 512

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 1000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
